// Batch 1 operations
pub mod blur;
pub mod resize;
pub mod threshold;
pub mod canny;
pub mod sobel;
pub mod box_blur;
pub mod laplacian;
pub mod flip;
pub mod erode;
pub mod dilate;
pub mod rotate;
pub mod scharr;
pub mod rgb_to_gray;
pub mod rgb_to_hsv;
pub mod adaptive_threshold;
pub mod hsv_to_rgb;
pub mod rgb_to_lab;
pub mod rgb_to_ycrcb;
pub mod bilateral_filter;
pub mod median_blur;

// Batch 2 operations
pub mod lab_to_rgb;
pub mod ycrcb_to_rgb;
pub mod pyrdown;
pub mod pyrup;
pub mod warp_affine;
pub mod convert_scale;
pub mod add_weighted;
pub mod gradient_magnitude;
pub mod distance_transform;
pub mod integral_image;
pub mod equalize_hist;
pub mod bitwise_not;
pub mod bitwise_and;
pub mod bitwise_or;
pub mod bitwise_xor;
pub mod absdiff;
pub mod min;
pub mod max;
pub mod add;
pub mod subtract;
pub mod multiply;
pub mod normalize;

// Export sync versions for native
#[cfg(not(target_arch = "wasm32"))]
pub use blur::gaussian_blur_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use resize::resize_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use threshold::threshold_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use canny::canny_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use sobel::sobel_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use box_blur::box_blur_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use laplacian::laplacian_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use flip::flip_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use erode::erode_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use dilate::dilate_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use rotate::rotate_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use scharr::scharr_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use rgb_to_gray::rgb_to_gray_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use rgb_to_hsv::rgb_to_hsv_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use adaptive_threshold::adaptive_threshold_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use hsv_to_rgb::hsv_to_rgb_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use rgb_to_lab::rgb_to_lab_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use rgb_to_ycrcb::rgb_to_ycrcb_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use bilateral_filter::bilateral_filter_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use median_blur::median_blur_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use lab_to_rgb::lab_to_rgb_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use ycrcb_to_rgb::ycrcb_to_rgb_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use pyrdown::pyrdown_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use pyrup::pyrup_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use warp_affine::warp_affine_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use convert_scale::convert_scale_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use add_weighted::add_weighted_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use gradient_magnitude::gradient_magnitude_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use distance_transform::distance_transform_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use integral_image::integral_image_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use equalize_hist::equalize_hist_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use bitwise_not::bitwise_not_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use bitwise_and::bitwise_and_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use bitwise_or::bitwise_or_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use bitwise_xor::bitwise_xor_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use absdiff::absdiff_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use min::min_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use max::max_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use add::add_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use subtract::subtract_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use multiply::multiply_gpu;
#[cfg(not(target_arch = "wasm32"))]
pub use normalize::normalize_gpu;

// Export async versions for WASM
pub use blur::gaussian_blur_gpu_async;
pub use resize::resize_gpu_async;
pub use threshold::threshold_gpu_async;
pub use canny::canny_gpu_async;
pub use sobel::sobel_gpu_async;
pub use box_blur::box_blur_gpu_async;
pub use laplacian::laplacian_gpu_async;
pub use flip::flip_gpu_async;
pub use erode::erode_gpu_async;
pub use dilate::dilate_gpu_async;
pub use rotate::rotate_gpu_async;
pub use scharr::scharr_gpu_async;
pub use rgb_to_gray::rgb_to_gray_gpu_async;
pub use rgb_to_hsv::rgb_to_hsv_gpu_async;
pub use adaptive_threshold::adaptive_threshold_gpu_async;
pub use hsv_to_rgb::hsv_to_rgb_gpu_async;
pub use rgb_to_lab::rgb_to_lab_gpu_async;
pub use rgb_to_ycrcb::rgb_to_ycrcb_gpu_async;
pub use bilateral_filter::bilateral_filter_gpu_async;
pub use median_blur::median_blur_gpu_async;
pub use lab_to_rgb::lab_to_rgb_gpu_async;
pub use ycrcb_to_rgb::ycrcb_to_rgb_gpu_async;
pub use pyrdown::pyrdown_gpu_async;
pub use pyrup::pyrup_gpu_async;
pub use warp_affine::warp_affine_gpu_async;
pub use convert_scale::convert_scale_gpu_async;
pub use add_weighted::add_weighted_gpu_async;
pub use gradient_magnitude::gradient_magnitude_gpu_async;
pub use distance_transform::distance_transform_gpu_async;
pub use integral_image::integral_image_gpu_async;
pub use equalize_hist::equalize_hist_gpu_async;
pub use bitwise_not::bitwise_not_gpu_async;
pub use bitwise_and::bitwise_and_gpu_async;
pub use bitwise_or::bitwise_or_gpu_async;
pub use bitwise_xor::bitwise_xor_gpu_async;
pub use absdiff::absdiff_gpu_async;
pub use min::min_gpu_async;
pub use max::max_gpu_async;
pub use add::add_gpu_async;
pub use subtract::subtract_gpu_async;
pub use multiply::multiply_gpu_async;
pub use normalize::normalize_gpu_async;
